version: '3.9'

services:
  minio:
    container_name: minio
    image: minio/minio:latest
    command: server --console-address ":9001" /data/
    environment:
      MINIO_ROOT_USER: 'cloudStorage'
      MINIO_ROOT_PASSWORD: 'minio123'
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - minio-storage:/data
    healthcheck:
      test: [ "CMD-SHELL", "mc ls myminio" ]
      interval: 30s
      timeout: 10s
      retries: 3
  mysql:
    image: mysql:8
    container_name: "mysql"
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: "2020"
      MYSQL_DATABASE: "security"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
  redis:
    container_name: redis
    image: redis:latest
    command: redis-server
    volumes:
      - ~/data/redis:/var/lib/redis
      - ~/data/redis/config:/usr/local/etc/redis/redis.conf
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      interval: 1s
      timeout: 3s
      retries: 5
  web:
    image: 'temas8150/javaweb:0.0.2'
    container_name: 'Storage'
    ports:
      - '8080:8080'
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:mysql://mysql:3306/security'
      spring.data.redis.host: 'redis'
      spring.data.redis.port: '6379'
      MINIO_URL: 'http://minio:9000'
      MINIO_ACCESS_NAME: 'cloudStorage'
      MINIO_ACCESS_SECRET: 'minio123'

    depends_on:
      mysql:
        condition: service_healthy
      minio:
        condition: service_healthy
      redis:
        condition: service_healthy
volumes:
  minio-storage:






