version: '3'

services:
  mysql:
    ports:
      - 3306:3306
    image: mysql:8
    container_name: java-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=2020
      - MYSQL_DATABASE=security
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10








