version: '3'

services:
  minio:
    image: minio/minio:latest
    command: server --console-address ":9001" /data/
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: cloudStorage
      MINIO_ROOT_PASSWORD: minio123
    volumes:
      - minio-storage:/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3
  mysql:
    ports:
      - 3306:3306
    image: mysql:8
    container_name: java-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=2020
      - MYSQL_DATABASE=security
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
  redis:
    image: redis:latest
    command: redis-server
    volumes:
      - ~/data/redis:/var/lib/redis
      - ~/data/redis/config:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      spring.jpa.database-platform: org.hibernate.dialect.MySQLDialect
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/security
      spring.datasource.username: root
      spring.datasource.password: 2020
      spring.data.redis.host: redis
      spring.data.redis.port: 6379
      MINIO_URL: http://minio:9000
      MINIO_ACCESS_NAME: cloudStorage
      MINIO_ACCESS_SECRET: minio123
      spring_data_redis_host: redis://redis:6379


    depends_on:
      - mysql
      - redis
      - minio
volumes:
  minio-storage:






